/**
 * Parse Apple .strings (UTF-8 / UTF-16 LE/BE) and .xcstrings catalogs.
 * Browser-safe: uses Uint8Array + TextDecoder (no Node Buffer).
 */

import { shouldSkipTranslation } from "./skip-heuristics";
import type { LocalizedString } from "./types";

export function decodeBytes(buf: Uint8Array): string {
  if (buf.length >= 2) {
    // UTF-16 LE BOM
    if (buf[0] === 0xff && buf[1] === 0xfe) {
      return new TextDecoder("utf-16le").decode(buf);
    }
    // UTF-16 BE BOM
    if (buf[0] === 0xfe && buf[1] === 0xff) {
      const swapped = new Uint8Array(buf.length - 2);
      for (let i = 2; i + 1 < buf.length; i += 2) {
        swapped[i - 2] = buf[i + 1];
        swapped[i - 1] = buf[i];
      }
      return new TextDecoder("utf-16le").decode(swapped);
    }
    // UTF-8 BOM
    if (buf[0] === 0xef && buf[1] === 0xbb && buf.length >= 3 && buf[2] === 0xbf) {
      return new TextDecoder("utf-8").decode(buf.subarray(3));
    }
    // Heuristic: many nulls → likely UTF-16 LE without BOM
    const sample = buf.subarray(0, Math.min(64, buf.length));
    let nulls = 0;
    for (let i = 0; i < sample.length; i++) if (sample[i] === 0) nulls++;
    if (nulls > sample.length / 4) {
      return new TextDecoder("utf-16le").decode(buf);
    }
  }
  return new TextDecoder("utf-8").decode(buf);
}

/** Unescape common .strings escape sequences */
function unescapeStringsValue(s: string): string {
  return s
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\t/g, "\t")
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, "\\");
}

/**
 * Parse classic .strings content:
 *   "key" = "value";
 */
export function parseStringsFile(
  content: string,
  filePath: string,
  locale: string
): LocalizedString[] {
  const results: LocalizedString[] = [];
  const withoutBlock = content.replace(/\/\*[\s\S]*?\*\//g, "\n");
  const cleaned = withoutBlock.replace(/^\s*\/\/.*$/gm, "");

  const pairRe = /"((?:\\.|[^"\\])*)"\s*=\s*"((?:\\.|[^"\\])*)"\s*;/g;
  let m: RegExpExecArray | null;
  let idx = 0;
  while ((m = pairRe.exec(cleaned)) !== null) {
    const key = unescapeStringsValue(m[1]);
    const value = unescapeStringsValue(m[2]);
    const { skip, reason } = shouldSkipTranslation(value);
    results.push({
      id: `${filePath}::${key}::${idx}`,
      key,
      value,
      locale,
      filePath,
      skip,
      skipReason: reason,
    });
    idx++;
  }
  return results;
}

export function serializeStringsFile(
  entries: { key: string; value: string }[]
): string {
  const escape = (s: string) =>
    s
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/\t/g, "\\t");

  const lines = [
    "/* Generated by IPA Translator — for legitimate localization only */",
    "",
  ];
  for (const e of entries) {
    lines.push(`"${escape(e.key)}" = "${escape(e.value)}";`);
  }
  lines.push("");
  return lines.join("\n");
}

type XcStringUnit = {
  state?: string;
  value?: string;
};

type XcEntry = {
  comment?: string;
  extractionState?: string;
  localizations?: Record<
    string,
    { stringUnit?: XcStringUnit; variations?: unknown }
  >;
};

type XcStringsCatalog = {
  sourceLanguage?: string;
  strings?: Record<string, XcEntry>;
  version?: string;
};

export function parseXcstringsFile(
  content: string,
  filePath: string
): LocalizedString[] {
  const results: LocalizedString[] = [];
  let catalog: XcStringsCatalog;
  try {
    catalog = JSON.parse(content) as XcStringsCatalog;
  } catch {
    return results;
  }
  const sourceLang = catalog.sourceLanguage || "en";
  const strings = catalog.strings || {};
  let idx = 0;
  for (const [key, entry] of Object.entries(strings)) {
    const locs = entry.localizations || {};
    let value: string | undefined;
    let locale = sourceLang;
    if (locs[sourceLang]?.stringUnit?.value != null) {
      value = locs[sourceLang].stringUnit!.value;
      locale = sourceLang;
    } else {
      const first = Object.entries(locs)[0];
      if (first?.[1]?.stringUnit?.value != null) {
        value = first[1].stringUnit!.value;
        locale = first[0];
      } else {
        value = key;
        locale = sourceLang;
      }
    }
    if (value == null) continue;
    const { skip, reason } = shouldSkipTranslation(value);
    results.push({
      id: `${filePath}::${key}::${idx}`,
      key,
      value,
      locale,
      filePath,
      comment: entry.comment,
      skip,
      skipReason: reason,
    });
    idx++;
  }
  return results;
}

export function localeFromPath(filePath: string): string {
  const m = filePath.match(/\/([A-Za-z]{2}(?:[-_][A-Za-z0-9]+)?)\.lproj\//);
  if (m) return m[1].replace("_", "-");
  if (/\/Base\.lproj\//i.test(filePath)) return "Base";
  if (filePath.endsWith(".xcstrings")) return "xcstrings";
  return "unknown";
}
