/**
 * Smoke test: parse fixtures/sample.ipa → local NLLB translate → write ZIP.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import AdmZip from "adm-zip";
import JSZip from "jszip";
import { pipeline, env } from "@xenova/transformers";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const fixture = path.join(root, "fixtures", "sample.ipa");
const MODEL = "Xenova/nllb-200-distilled-600M";

env.cacheDir = path.join(root, ".cache");
env.allowLocalModels = true;
env.allowRemoteModels = true;

function decodeBuffer(buf) {
  if (buf.length >= 2 && buf[0] === 0xff && buf[1] === 0xfe) {
    return buf.toString("utf16le");
  }
  return buf.toString("utf8");
}

function parseStrings(content) {
  const pairRe = /"((?:\\.|[^"\\])*)"\s*=\s*"((?:\\.|[^"\\])*)"\s*;/g;
  const out = [];
  let m;
  while ((m = pairRe.exec(content)) !== null) {
    out.push({ key: m[1], value: m[2] });
  }
  return out;
}

function protectPlaceholders(text) {
  const tokens = [];
  const protectedText = text.replace(
    /%%|%(?:\d+\$)?(?:[-+0 #]*)?(?:\d+|\*)?(?:\.(?:\d+|\*))?(?:hh|h|ll|l|L|z|t|j)?[@dioxXufFeEgGaAcspSn%]/g,
    (m) => {
      tokens.push(m);
      return `[PH${tokens.length - 1}]`;
    }
  );
  const restore = (translated) => {
    let out = translated;
    tokens.forEach((token, idx) => {
      const patterns = [
        `\\[\\s*PH\\s*${idx}\\s*\\]`,
        `#\\s*PH\\s*${idx}\\s*#`,
        `(?<![A-Za-z0-9])PH\\s*${idx}(?![A-Za-z0-9])`,
      ];
      for (const src of patterns) {
        if (new RegExp(src, "gi").test(out)) {
          out = out.replace(new RegExp(src, "gi"), token);
          break;
        }
      }
    });
    return out;
  };
  return { protectedText, restore };
}

async function translateLocal(texts) {
  console.log(`Loading local model ${MODEL} (cache: ${env.cacheDir})...`);
  const translator = await pipeline("translation", MODEL);
  const results = [];
  for (const text of texts) {
    const out = await translator(text, {
      src_lang: "eng_Latn",
      tgt_lang: "arb_Arab",
      max_new_tokens: 256,
    });
    const item = Array.isArray(out) ? out[0] : out;
    results.push(item.translation_text);
  }
  return results;
}

async function main() {
  if (!fs.existsSync(fixture)) {
    console.error("Missing fixture:", fixture);
    process.exit(1);
  }

  const zip = new AdmZip(fixture);
  const entries = zip.getEntries().filter((e) => !e.isDirectory);
  console.log(
    "IPA entries:",
    entries.map((e) => e.entryName)
  );

  const stringsEntry = entries.find((e) =>
    e.entryName.endsWith("Localizable.strings")
  );
  if (!stringsEntry) {
    console.error("No Localizable.strings in fixture");
    process.exit(1);
  }

  const content = decodeBuffer(stringsEntry.getData());
  const pairs = parseStrings(content);
  console.log(`Parsed ${pairs.length} strings from fixture`);

  const sample = pairs
    .filter(
      (p) =>
        !/^https?:/i.test(p.value) &&
        !p.value.includes("@example") &&
        !p.value.startsWith("com.")
    )
    .filter((p) => !p.value.includes("%"))
    .slice(0, 3);

  const withPh = pairs.find((p) => p.value.includes("%@"));
  if (withPh) sample.push(withPh);

  const protectedList = sample.map((p) => protectPlaceholders(p.value));
  const raws = await translateLocal(protectedList.map((p) => p.protectedText));

  let failed = false;
  const translated = [];
  for (let i = 0; i < sample.length; i++) {
    const p = sample[i];
    const t = protectedList[i].restore(raws[i]);
    console.log(`  ${p.key}: "${p.value}" → "${t}"`);
    if (!t || !t.trim()) {
      console.error("  FAIL: empty translation");
      failed = true;
    }
    if (p.value.includes("%@") && !t.includes("%@")) {
      console.warn("  WARN: placeholder %@ was not preserved:", t);
      failed = true;
    }
    if (!p.value.includes("%") && !/[\u0600-\u06FF]/.test(t)) {
      console.warn("  WARN: expected Arabic characters in translation:", t);
      failed = true;
    }
    translated.push({ key: p.key, value: t });
  }

  const outZip = new JSZip();
  const lines = [
    "/* Generated by IPA Translator smoke test (local NLLB) */",
    "",
    ...translated.map(
      (e) => `"${e.key}" = "${e.value.replace(/"/g, '\\"')}";`
    ),
    "",
  ];
  outZip.file(
    "Payload/SampleApp.app/ar.lproj/Localizable.strings",
    lines.join("\n")
  );
  const buf = await outZip.generateAsync({ type: "nodebuffer" });
  const outPath = "/tmp/ipa-translator-smoke-ar.zip";
  fs.writeFileSync(outPath, buf);
  console.log("Wrote", outPath, `(${buf.length} bytes)`);
  console.log(`Engine: @xenova/transformers ${MODEL} (offline)`);
  if (failed) {
    console.error("SMOKE FAILED");
    process.exit(1);
  }
  console.log("SMOKE OK");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
