/**
 * Smoke test: parse fixtures/sample.ipa → translate a few strings → write ZIP.
 * Also hits the Next.js API routes when SERVER_URL is set (optional).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import AdmZip from "adm-zip";
import JSZip from "jszip";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const fixture = path.join(root, "fixtures", "sample.ipa");

function decodeBuffer(buf) {
  if (buf.length >= 2 && buf[0] === 0xff && buf[1] === 0xfe) {
    return buf.toString("utf16le");
  }
  return buf.toString("utf8");
}

function parseStrings(content) {
  const pairRe = /"((?:\\.|[^"\\])*)"\s*=\s*"((?:\\.|[^"\\])*)"\s*;/g;
  const out = [];
  let m;
  while ((m = pairRe.exec(content)) !== null) {
    out.push({ key: m[1], value: m[2] });
  }
  return out;
}

function protectPlaceholders(text) {
  const tokens = [];
  const protectedText = text.replace(
    /%%|%(?:\d+\$)?(?:[-+0 #]*)?(?:\d+|\*)?(?:\.(?:\d+|\*))?(?:hh|h|ll|l|L|z|t|j)?[@dioxXufFeEgGaAcspSn%]/g,
    (m) => {
      tokens.push(m);
      return `⟦PH${tokens.length - 1}⟧`;
    }
  );
  const restore = (translated) => {
    let out = translated;
    tokens.forEach((token, idx) => {
      const re = new RegExp(`⟦\\s*PH\\s*${idx}\\s*⟧`, "gi");
      out = out.replace(re, token);
      out = out.replace(new RegExp(`__\\s*PH\\s*[_\s-]*${idx}\\s*__`, "gi"), token);
    });
    return out;
  };
  return { protectedText, restore };
}

async function translateMyMemory(text, target = "ar") {
  const params = new URLSearchParams({
    q: text,
    langpair: `en|${target}`,
  });
  const res = await fetch(
    `https://api.mymemory.translated.net/get?${params}`
  );
  const data = await res.json();
  if (data.responseStatus !== 200) return text;
  const t = data.responseData?.translatedText || text;
  if (/MYMEMORY WARNING|QUOTA EXCEEDED/i.test(t)) return text;
  return t;
}

async function main() {
  if (!fs.existsSync(fixture)) {
    console.error("Missing fixture:", fixture);
    process.exit(1);
  }

  const zip = new AdmZip(fixture);
  const entries = zip.getEntries().filter((e) => !e.isDirectory);
  console.log(
    "IPA entries:",
    entries.map((e) => e.entryName)
  );

  const stringsEntry = entries.find((e) =>
    e.entryName.endsWith("Localizable.strings")
  );
  if (!stringsEntry) {
    console.error("No Localizable.strings in fixture");
    process.exit(1);
  }

  const content = decodeBuffer(stringsEntry.getData());
  const pairs = parseStrings(content);
  console.log(`Parsed ${pairs.length} strings from fixture`);

  // Prefer UI strings; still include one with placeholder
  const sample = pairs
    .filter(
      (p) =>
        !/^https?:/i.test(p.value) &&
        !p.value.includes("@example") &&
        !p.value.startsWith("com.")
    )
    .filter((p) => !p.value.includes("%"))
    .slice(0, 3);

  const withPh = pairs.find((p) => p.value.includes("%@"));
  if (withPh) sample.push(withPh);

  const translated = [];
  for (const p of sample) {
    const { protectedText, restore } = protectPlaceholders(p.value);
    const raw = await translateMyMemory(protectedText, "ar");
    const t = restore(raw);
    console.log(`  ${p.key}: "${p.value}" → "${t}"`);
    if (p.value.includes("%@") && !t.includes("%@")) {
      console.warn("  WARN: placeholder %@ was not preserved:", t);
    }
    translated.push({ key: p.key, value: t });
  }

  const outZip = new JSZip();
  const lines = [
    "/* Generated by IPA Translator smoke test */",
    "",
    ...translated.map((e) => `"${e.key}" = "${e.value.replace(/"/g, '\\"')}";`),
    "",
  ];
  outZip.file(
    "Payload/SampleApp.app/ar.lproj/Localizable.strings",
    lines.join("\n")
  );
  const buf = await outZip.generateAsync({ type: "nodebuffer" });
  const outPath = "/tmp/ipa-translator-smoke-ar.zip";
  fs.writeFileSync(outPath, buf);
  console.log("Wrote", outPath, `(${buf.length} bytes)`);
  console.log("SMOKE OK");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
